server:
  port: 8080

datasource:
  shards:
    - hash: 0
      url: jdbc:postgresql://localhost:5550/employee
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 10000
        max-lifetime: 30000
        auto-commit: true
    - hash: 1
      url: jdbc:postgresql://localhost:5551/employee
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 10000
        max-lifetime: 30000
        auto-commit: true
    - hash: 2
      url: jdbc:postgresql://localhost:5552/employee
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
      hikari:
        connection-timeout: 20000
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 10000
        max-lifetime: 30000
        auto-commit: true

spring:
  application:
    name: 'DB - Sharding'
  flyway:
    enabled: false
    locations: classpath:db/migration

  main:
    banner-mode: 'off'
  graphql:
    graphiql:
      enabled: true
    tools:
      schema-parser-options:
        introspection-enabled: false
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include:
          - info
          - health
          - metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  health:
    db:
      enabled: false
  statsd:
    metrics:
      export:
        host: ${DD_AGENT_HOST:172.17.0.1}
        port: 8125
        flavor: datadog
    enable:
      all: true